### ISSUE TITLE
[macos] Fix dependencies

### ISSUE THREAD

**Issue by medecau** [PyUserInput/PyUserInput#11]
Starting this issue to have a public record of what I'm doing.
This is MACOS specific. Reply if you can help.

Objective is to install all dependencies from the install process.
Users with a fresh environment must have all dependencies installed for them by calling `pip install pyuserinput`.

**Comment by medecau** [comment]
There are two documented requirements for macos in the README.

 - Quartz
 - AppKit

Quartz seems to be available under the pypi pyobjc-framework-Quartz package. Which is part of pyobjc[1] project. It might be wise to depend on the whole project instead of only part of it.

While installing pyobjc I was blocked by a known bug[2] and had to install from source. This is less than ideal.

Appkit is available in pypi as AppKit so installation is trivial.


[1] https://bitbucket.org/ronaldoussoren/pyobjc/overview
[2] https://bitbucket.org/ronaldoussoren/pyobjc/issues/151/pyobjc-fails-to-compile-on-macos-x-1010

**Comment by medecau** [comment]
test_unix.py uses pyvirtualdisplay which is not mentioned anywhere.

pyvirtualdisplay needs at least one of Xvfb, Xephyr, or Xvnc.

**Comment by medecau** [comment]
Tests ran to completion for the first time with no errors. Some tests failed though.

**Comment by medecau** [comment]
AppKit depends on PyGObject and cannot be installed as a requirement.
I cannot currently replicate but it seems I got it installed with pyobjc.

**Comment by pepijndevos** [comment]
I think everything we use is part of pyobjc. iirc the Python that ships with os X has pyobjc preinstalled. I'll be near my Mac next week, so I could help out a bit maybe.

**Comment by moses-palmer** [comment]
For *pynput* I require only *pyobj**-framework-Quartz* (
https://github.com/moses-palmer/pynput/blob/master/setup.py#L30), and it
builds in a virtualenv without access to the system libraries.

The version required in that library is higher that what is shipped by Mac
OSX however. I think *PyUserInput* does not require anything not shipped by
default, so it should be safe to use a lower version.

**Comment by medecau** [comment]
@pepijndevos I am using the homebrew version. I assume most people use that or some other non-default python.

**Comment by pepijndevos** [comment]
True for developers, the users of your software probably use system python.
But anyway, it should be a dependency,

Note that some things we use might be available in different places, so by
looking closer at the imports we might be able to remove dependency on
AppKit for example.
I probably just imported whatever the Objective C or Python code on some
random forum or mailing list imported it from.

**Comment by pepijndevos** [comment]
@moses-palmer it does seem you use AppKit as well. So is @medecau correct that's a part of Quartz?

https://github.com/moses-palmer/pynput/blob/master/lib/pynput/mouse/_darwin.py#L21

**Comment by moses-palmer** [comment]
I guess ;-) As I indicated earlier, depending solely on Quartz satisfies
all dependencies, so it builds successfully in a virtualenv with no access
to external libraries.

**Comment by medecau** [comment]
@pepijndevos I lied.
AppKit does depend on pygobject(not to be confused with pyobjc) but I got that installed with homebrew.
pygobject seems to be harder to install than pyobjc.

I am currently exploring two things.

- how to inform users they need Quartz and AppKit AND their respective dependencies.
- automate the installation of these dependencies.

In order to better inform users I'm exploring printing relevant messages at install time. Possibly pointing to the README for further help.

Automating installation of the dependencies would be really good for testing purposes.

**Comment by pepijndevos** [comment]
Okay, I know what's going on. Hold on to your seats.

I checked the deps, and `pyobjc-framework-Quartz` depends on `pyobjc-framework-Cocoa` which *provides* `AppKit`.

Here is the mindfuck: The PyPi package called AppKit is actually a completely different thing related to Webkit and Gnome.

This also explains the gobject dependency, which is the object system used in GTK.

**Comment by pepijndevos** [comment]
Ugh, I nicely split up the version bump and dependency change, and then messed up and threw everything together. Sorry for the mess...
