### ISSUE TITLE
Is it possible to supress output?

### ISSUE THREAD

**Issue by jurgenhaas** [PyUserInput/PyUserInput#17]
I have a simple subclass of PyKeyboardEvent and implemented `tap()` which checks for a special key I defined and that is executing my stuff. All of that is working great, but still the original event is still executed as well. Is there a way to supress that original event?

Also, when I start my script in the console, sometimes I find messages like this in that console:

```
Unable to determine character.
Keycode: 116 KeySym 0
```

I know I could pipe the output to /dev/null but I wonder if there was a flag for PyUserInput that would switch to silent mode.

**Comment by pepijndevos** [comment]
I'm a bit busy, so I can't check. On the mouse side (which I wrote) we support a capture parameter, which would do what you want. I'm not sure about the keyboard side.I imagine the proper API would be to return the event if you want to propagate and return none to capture, but this is evidently not how it works.                                                                                                                                      Alternatively, wait for @moses-palmer to chime in how to do this in pynput, which I'm starting to believe is just a better library.                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.

**Comment by jurgenhaas** [comment]
Thanks @pepijndevos for the hint. There is in fact a capture parameter in PyKeyboardEventMeta too, but regardless of what I'm setting this to, it doesn't seem to have any effect. So I'll wait for @moses-palmer to hoprefully throw some more light one this.

**Comment by jurgenhaas** [comment]
@moses-palmer any chance you could have a look into this please?

**Comment by moses-palmer** [comment]
@jurgenhaas There is a [feature request](https://github.com/moses-palmer/pynput/issues/3) open for similar functionality.

I will look into whether it is possible for all supported platforms.

**Comment by moses-palmer** [comment]
I have looked into the *Xlib* documentation, and I have not found any way to suppress or modify keyboard events. The `capture` parameter used by the mouse implementation simply calls methods to grab the pointer.

On *win32*, it appears that it is likewise impossible to alter the event.

On *OSX*, it is possible to modify keyboard events before they are propagated to the rest of the system; I suppose this also allows suppressing events.

Given that, presumably, only one of the supported platforms support this functionality, I am very hesitant to add it to either *PyUserInput* or *pystray*.

**Comment by jurgenhaas** [comment]
Thanks a lot @moses-palmer for looking into this. Maybe some review of Autokey maybe worth it as they seem to got it sorted. There is

- https://code.google.com/archive/p/autokey for Python 2
- https://github.com/autokey-py3/autokey-py3 for Python 3

**Comment by moses-palmer** [comment]
A quick question, as I don't have time at the moment to read the full
*autokey* documentation at the moment: what part of autokey implements the
feature that you are looking for? At a quick glance, I see no obvious wait
to monitor arbitrary keys and suppress or modify them.

**Comment by jurgenhaas** [comment]
Autokey also runs in the background and let's you define global keys combinations that execute scripts that you also define in their UI.

I guess the relevant part is happening in their Service class where I found a handle_keypress method which probably does the magic.

**Comment by moses-palmer** [comment]
That is what I suspected.

So you need to specify a key combination to use beforehand? My quick glance
at the code gave me there impression that they use global hotkeys. This
would explain why the key presses are suppressed.

If so, it cannot really be used to suppress arbitrary key strokes I think.

**Comment by jurgenhaas** [comment]
Ah, I start to understand the difference. Pre-registered key-combinations are recognized differently from listening to all keyboard events, which is what PyUserInput is doing.

**Comment by moses-palmer** [comment]
That is correct :-)

Most windowing systems allow registering global hotkeys. They will
generally be sent to one client only.

PyUserInput provides a way to listen to input events, but they cannot
generally be modified or suppressed.

Can we close this issue?

**Comment by jurgenhaas** [comment]
Yes, thanks anyway.
