### ISSUE TITLE
Pymouse.screen_size() and Pymouse.position() cause Python launcher to appear os macOS

### ISSUE THREAD

**Issue by Property404** [PyUserInput/PyUserInput#18]
On macOS Sierra  
Latest pip3(9.0.1)
Latest PyUserInput according to `pip3 list --outdated`  
Latest Python3 according to brew(3.6.0)  

How to reproduce:  
on macOS Sierra, open terminal, type `python3`(brew installed)  
type `from pymouse import PyMouse`  
type `m = PyMouse()`  
type `m.position()`  
Python launcher will pop up in dock  

Expected behavior: Python launcher shouldn't pop up in the dock  

This only happens with these two methods, all other methods are find. No other problems are found with the methods. (that I know of)

**Comment by pepijndevos** [comment]
I'm going to close as WONTFIX.
This is a direct result of the underlying PyObjC API functions we use.
Some API's only works from an App bundle, so PyObjC helps you out here by starting an App for you. This does not happen if you're already running as an App bundle.

The only fix would be to use different (probably more low-level) API calls.
Feel free to re-open if you know any suitable API.
