### ISSUE TITLE
The Licensing Question

### ISSUE THREAD

**Issue by SavinaRoja** [PyUserInput/PyUserInput#3]
There has been occasional mention of altering the licensing of PyUI. I think both @pepijndevos and I are: open to changing the licensing, amenable to a more relaxed license (perhaps the lgpl).

Of course, it's best to not be hasty with this sort of thing so I wanted to put this out in the public for a little bit to mull over. I'd be happy to hear thoughts and considerations from others, especially (perhaps needfully?) from our other contributors.

So, how should PyUI be licensed?

_Releasing under multiple licenses appears to be something that has occurred occasionally, but looks sketchy, tenuous, and not advisable for non-lawyers._

**Comment by moses-palmer** [comment]
I fully support switching to LGPL.

At my previous job, I had enough trouble trying to decipher various licences, and came to enjoy the clear position taken by that licence and its trying to please everyone.

**Comment by Sebelino** [comment]
Thanks for bringing this up; this reminded me that my PyUI-dependent application ([kecomp](https://github.com/Sebelino/kecomp)) was wrongfully licensed under GPLv2 until I changed it to GPLv3 a few minutes ago.

I agree that LGPL makes more sense here.

**Comment by pepijndevos** [comment]
That's two votes for LGPL.

@casebeer do you have any input? Since you brought it up before.

Do we need to officially go ask all contributors ever for permission to do this, or can we just replace the file and be done?

**Comment by casebeer** [comment]
I agree LGPL would be preferable. 

Last year I filed a PR on both PyUserInput and PyMouse since I'm using PyMouse in preference to PyUserinput to allow my project to continue to be BSD rather than GPL licensed. Having a more relaxed (and more compatible) license for PyUserInput would be great. 

I'm certainly fine with my changes being relicensed.

**Comment by pepijndevos** [comment]
Go forth and use PyUsedInput in all your cute weirdly licensed projects.
