### ISSUE TITLE
How to record input from keyboard with time interval and simulate the exact input process?

### ISSUE THREAD

**Issue by LinearFreddie** [PyUserInput/PyUserInput#48]
I want to create a script where it can monitor the whole process of keyboard input (with time interval, more like a log) and output the exact same events. Can anyone tell me how to deal with the time interval? 
This one is for an auto driving process in FORZA HORIZON 4. I really want to know if it's achievable. And in the exact same race I don't want to use deep learning so far. Thank you for reading.

**Comment by moses-palmer** [comment]
You will want to log the following information for each event received in the listener callback:

* **The timestamp**. This is not included in the event, so you'll have to use a standard module.
* **The virtual key code**. This will simplify writing and interpreting the log, but you will not be able to use the data on other platforms.
* **Whether the event was a press or release type.**

When replaying, you simply create key code instance using [`KeCode.from_vk`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L113) and pad it to [`Controller.touch`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L414) along with the pressed-or-released flag.

You will then need to sleep a duration determined by the time between the current event and the next one before proceeding.
