### ISSUE TITLE
Pymouse .run() doesn't resume function after .stop is called()

### ISSUE THREAD

**Issue by joaomamede** [PyUserInput/PyUserInput#55]
This was working 3/4 years ago when I wrote it and now it's buggy.

```
from pymouse import PyMouse
from pymouse import PyMouseEvent
from pykeyboard import PyKeyboard
import pyperclip
import numpy as np
m = PyMouse()
k = PyKeyboard()



class set_position(PyMouseEvent):
    def __init__(self):
        PyMouseEvent.__init__(self)

    def click(self,x,y,button,press):
        if button == 1:
            if press:
               self.value = m.position()
               print self.value
        else:
            print "aborted"
            self.stop()
```

Then in my main program:

This is how it was and it was running fine in previous versions.

```
    print "Please Click on a section without text"
    scan_button = set_position()
    scan_button.run()
    scan_x, scan_y = scan_button.value
```

When I clicked with button 1 it would set the value, correctly and when I clicked middle or button 2, it would resume the python script or, go back to prompt.

Now it gets stuck.
if I put prints on the "if button ==1" then and else. It does capture mouse events until I press any other button. But then it gets stuck until ctrl+c is pressed many many times.

if I switch to 

```
    print "Please Click on a section without text"
    scan_button = set_position()
    scan_button.start()
    scan_x, scan_y = scan_button.value
```

It comes back to the python shell but value was never defined because it runs in the background and proceeds right away.

Am I doing something wrong that doesn't match most recent versions? Thanks

**Comment by joaomamede** [comment]
By the way. 

The clickonacci.py  code has the exact same problem.

**Comment by TomRoussel** [comment]
I ran into the same issue, and narrowed the problem down to the context manager in x11.py, on linux. I'm not sure why, but PyMouseEvent keeps 2 x11 Display objects. When stop() is called, it calls Display.sync() on both objects. That second call blocks forever. I patched it with this:

`diff --git a/pymouse/x11.py b/pymouse/x11.py
index 524ba77..5299f94 100644
--- a/pymouse/x11.py
+++ b/pymouse/x11.py
@@ -198,9 +198,9 @@ class PyMouseEvent(PyMouseEventMeta):
         with display_manager(self.display) as d:
             d.ungrab_pointer(X.CurrentTime)
             d.record_disable_context(self.ctx)
-        with display_manager(self.display2) as d:
-            d.ungrab_pointer(X.CurrentTime)
-            d.record_disable_context(self.ctx)
+
+        self.display2.ungrab_pointer(X.CurrentTime)
+        self.display2.record_disable_context(self.ctx)
 
     def handler(self, reply):
         data = reply.data
`

It seems to work as expected now.

**Comment by pepijndevos** [comment]
The reason there are two displays had something to do that you can't do two things at the same time with one context, forgot the details.

I would be happy to click the merge button if you submitted this as a PR. But in general I'm not really maintaining this library anymore and suggest people use Pynput instead. If anyone is interested to take on maintenance of the project, do let me know.

Basically the reason I'm recommending Pynput is that our windows support depends on a dead py2 library, and we don't handle keyboard layouts at all basically.

**Comment by TomRoussel** [comment]
Ok, thanks for the suggestion! I'll check out Pynput.
I'll create a pull request for this anyways, in case somebody has some old scripts lying around that might benefit from this.
