### ISSUE TITLE
Capture both PyMouseEvent and PyKeyboardEvent

### ISSUE THREAD

**Issue by jnweiger** [PyUserInput/PyUserInput#6]
I'd like to write an on-screen keyboard + mouse logger. Purpose enable podcast or workshop audience to see which keys I type, especially CTRL SHIFT, LMB, RMB. 

From looking at the run() methods, it appears I have to choose either mouse or keyboard, but having both is not possible. Correct?

**Comment by Sebelino** [comment]
I don't see why it wouldn't be possible. Just create separate threads.

Here is an example where I create one thread for handling key events, one for handling mouse events and one main thread:

https://gist.github.com/Sebelino/e9ad3b4321e489d5ece69bf70f4e1d92

**Comment by jnweiger** [comment]
Okay, threading is a nice workaround here :-) thank you!
